# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hilleldb
      MYSQL_USER: hillel
      MYSQL_PASSWORD: Hillel1234
    # (this is just an example, not intended to be a production configuration)
